version: "3.8"

services:
  pgdog:
    build: . 
    volumes:
      - ./docker/pgdog.toml:/pgdog/pgdog.toml
      - ./docker/users.toml:/pgdog/users.toml
    ports:
      - "6432:6432"
      - "9090:9090"  # Prometheus
    networks:
      - postgres
    environment:
      RUST_LOG: debug

  shard_0:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres

  shard_1:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres

  shard_2:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - postgres

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - postgres
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  postgres:
