global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pgdog'
    scrape_timeout: 5s
    scheme: http
    metrics_path: /metrics
    fallback_scrape_protocol: PrometheusText0.0.4  
    static_configs:
      - targets: ['pgdog:9090']

